### ISSUE TITLE
What does "ScalingRule" in "BMD.INF1.cs" do?

### ISSUE THREAD

**Issue by MichaelHinrichs** [SuperHackio/Hack.io#1]
Hack.io is the only BMD program that seems to know what to do with those 2 bytes. All the others, like J3D Model viewer and superBMD just skip over them or name them "unknown". Even the Mario Kart Hacking Wiki doesn't know that to do with it. It says it's 01 for BMD & 00 for BDL, but that's incorrect.
Wind Waker, and both Mario Galaxy games have BDL files with 00. Twilight Princess has BMD files that say 00. Mario Sunshine has BMDs that are 01. And BDL playermodels in Wind Waker, and Galaxy have a 02s.

**Comment by SuperHackio** [comment]
Excellent question
Because Hack.io.BMD is not sourced from a single location, the ScalingRule came from [NoClip.Website's Source Code](https://github.com/magcius/noclip.website/blob/8b0de601d6d8f596683f0bdee61a9681a42512f9/src/Common/JSYSTEM/J3D/J3DLoader.ts#L81)

As for what it actually does..... It doesn't actually affect anything in Hack.io.BMD (And seemingly affects nothing in NoClip.Website). Hack.io.BMD reads/writes the value to make sure the correct value gets saved

**Comment by MichaelHinrichs** [comment]
I see. Thank you for answering. I guess I'll go ask Jasper.

**Comment by SuperHackio** [comment]
Let me know if it does actually do something :eyes:

**Comment by SuperHackio** [comment]
Okay I did a bit more research, it's related to animation playing.

**Comment by MichaelHinrichs** [comment]
He wasn't very helpful.

https://github.com/magcius/noclip.website/issues/476

**Comment by SuperHackio** [comment]
Should've seen that coming

In short, the BASIC scaling rule probably means whatever the universal scaling math is
XSI would use math that's seen in Softimage XSI 3D Images
MAYA would use math that's present in Autodesk's Maya program
And then there's MASK.....It probably means that something in-game overrides the values in the BMD/BDL

References to the LoadFlags are as follows (this isn't all of them, just the main ones)
https://github.com/magcius/noclip.website/blob/c8e8f67b7a0b0fadd2238c41cd40932e13df607c/src/Common/JSYSTEM/J3D/J3DGraphSimple.ts
https://github.com/magcius/noclip.website/blob/c8e8f67b7a0b0fadd2238c41cd40932e13df607c/src/Common/JSYSTEM/J3D/J3DGraphAnimator.ts
https://github.com/magcius/noclip.website/blob/a521f6273fdce0ec9e10435f74d6f62294eb2c5b/src/Common/JSYSTEM/J3D/J3DGraphBase.ts

**Comment by magcius** [comment]
In theory, this flag changes how skeleton matrices are calculated. JSYSTEM uses completely different recursive procedures for Basic / Maya / XSI depending on the matrix calculation flag. In practice, I believe the only difference is that the Maya mode supports [Segment Scale Correction](https://download.autodesk.com/us/fbx/FBX_Maya_online/files/WS73099cc142f48755-3d114b751181c40f14b1283.htm). There's something similar for XSI, though I haven't found a test case for it yet. There is a similar flag in BRRES's MDL0, but in there, it also adds support for a 3DS Max calculation mode.

Mask is just because the original library does `& 0x0F` before checking the enum entry from the load flags. You should never see it in there on valid BMD/BDL files.

The SSC flag itself can be found on each matrix entry in the JNT1 section.

If you want a good test model, I originally implemented this for Super Mario Galaxy's LavaGeiser which can be found in Freezeflame Galaxy. It should look a bit like a tall finger if implemented correctly; if implemented wrong, it will spread into a wide flat pool.

**Comment by SuperHackio** [comment]
You know, that probably explains why they look so wide in Whitehole (It's renderer is very old)
![image](https://user-images.githubusercontent.com/44330283/143799682-2102d491-84db-41b3-a3b0-c9cdebba5823.png)
![image](https://user-images.githubusercontent.com/44330283/143799702-f9b415d7-ef36-4305-a814-fb5360665a33.png)
